# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 898c7fb593d75a2394d20a1c39b087775d91c92ad47fb9bf70b13966d8b411c056cff2cf2214b87fa500cd1976973781dc8c8150b7d72e696194133805e4155a

test:
  secret_key_base: 36b81be5c1e2165e1ac2ac70bd6e939ec545ab1c805433327dc03271df2f19fadd6302719b289aa9d5d457a77753307c13d0753dcc81ba93066d1f5c1db62818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
